import jsPDF from "jspdf";

export function generatePDF(history, user) {
  const doc = new jsPDF();
  const name = user?.displayName || user?.email || "User";
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("AI Farmer", 14, 14);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Prediction History Report — ${name} — ${date}`, 14, 23);

  doc.setTextColor(0, 0, 0);
  let y = 40;

  history.forEach((h, i) => {
    if (y > 260) { doc.addPage(); y = 20; }

    // Card background
    doc.setFillColor(240, 253, 244);
    doc.roundedRect(10, y, 190, 28, 3, 3, "F");

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(21, 128, 61);
    doc.text(`${i + 1}. ${h.type?.toUpperCase()} PREDICTION`, 15, y + 8);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(10);
    doc.text(`Result: ${h.result || "N/A"}`, 15, y + 16);

    const dateStr = h.createdAt?.toDate?.()?.toLocaleDateString() || "";
    doc.setTextColor(120, 120, 120);
    doc.setFontSize(9);
    doc.text(dateStr, 170, y + 8);

    if (h.inputs) {
      const inputStr = Object.entries(h.inputs).slice(0, 5).map(([k, v]) => `${k}: ${v}`).join("  |  ");
      doc.setTextColor(80, 80, 80);
      doc.setFontSize(8);
      doc.text(inputStr, 15, y + 23);
    }

    y += 34;
  });

  // Footer
  doc.setFillColor(34, 197, 94);
  doc.rect(0, 285, 210, 12, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text("Generated by AI Farmer System  |  Empowering Farmers with AI", 14, 292);

  doc.save(`crop-advisory-history-${date}.pdf`);
}
